//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCitySuburb
    {
        public int PKID { get; set; }
        public int FK_CityID { get; set; }
        public int FK_SuburbID { get; set; }
    }
}
