//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UnitransTestSystemsDBEntities : DbContext
    {
        public UnitransTestSystemsDBEntities()
            : base("name=UnitransTestSystemsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCity> tblCities { get; set; }
        public DbSet<tblCitySuburb> tblCitySuburbs { get; set; }
        public DbSet<tblSuburb> tblSuburbs { get; set; }
        public DbSet<tblUserDetail> tblUserDetails { get; set; }
    
        public virtual ObjectResult<prc_GetCity_Result> prc_GetCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetCity_Result>("prc_GetCity");
        }
    
        public virtual ObjectResult<prc_GetSuburb_Result> prc_GetSuburb(Nullable<int> pCityID)
        {
            var pCityIDParameter = pCityID.HasValue ?
                new ObjectParameter("pCityID", pCityID) :
                new ObjectParameter("pCityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetSuburb_Result>("prc_GetSuburb", pCityIDParameter);
        }
    
        public virtual ObjectResult<prc_GetUserDetailsByLookupText_Result> prc_GetUserDetailsByLookupText(string pLookupText)
        {
            var pLookupTextParameter = pLookupText != null ?
                new ObjectParameter("pLookupText", pLookupText) :
                new ObjectParameter("pLookupText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetUserDetailsByLookupText_Result>("prc_GetUserDetailsByLookupText", pLookupTextParameter);
        }
    
        public virtual ObjectResult<prc_GetUserDetailsBySearchText_Result> prc_GetUserDetailsBySearchText(string pSearchText)
        {
            var pSearchTextParameter = pSearchText != null ?
                new ObjectParameter("pSearchText", pSearchText) :
                new ObjectParameter("pSearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetUserDetailsBySearchText_Result>("prc_GetUserDetailsBySearchText", pSearchTextParameter);
        }
    }
}
